### ISSUE TITLE
[bug] AbstractMethodError: org.pitest.junit5.JUnit5Configuration.testClassIdentifier() when running pitest task

### ISSUE THREAD

**Issue by damienbeaufils** [pitest/pitest-junit5-plugin#3]
## Description
When trying to run pitest with pitest-junit5-plugin v0.3, pitest v1.3.1 and gradle v4.4.1, I ran into this error:
```
Exception in thread "main" java.lang.AbstractMethodError: org.pitest.junit5.JUnit5Configuration.testClassIdentifier()Lorg/pitest/testapi/TestClassIdentifier;
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:98)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:49)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
```
A full build stacktrace is available [here](https://travis-ci.org/damienbeaufils/clean-architecture-demo/jobs/329382180).
If I revert pitest-junit5-plugin to v0.2 and pitest to v1.2.5, it works fine.

## How to reproduce it
Checkout this repository: https://github.com/damienbeaufils/clean-architecture-demo
And run `./gradlew pitest` to compile and execute `pitest` task

**Comment by hcoles** [comment]
There is some sort of error in the gradle file so that the configured version of pitest is not picked up.

I don't work with gradle much so I'm afraid I can't see what the issue is, but if I change    

`pitestVersion = "${pitestVersion}"`

To

`pitestVersion = "1.3.1"`

Then the correct version is picked up and the AbstractMethodError goes away.

Unfortunately this doesn't solve all your problems as it isn't currently possible to configure pitest to use the junit 5 plugin via gradle (see https://github.com/szpak/gradle-pitest-plugin/issues/76)

**Comment by damienbeaufils** [comment]
@hcoles Thanks!
So I'll wait for https://github.com/szpak/gradle-pitest-plugin/issues/76 to be resolved.
In the meantime I close this issue.
