### ISSUE TITLE
Coverage generator Minion exited abnormally due to UNKNOWN_ERROR

### ISSUE THREAD

**Issue by MosheElisha** [pitest/pitest-junit5-plugin#49]
Hi,

When I run `mvn clean test org.pitest:pitest-maven:mutationCoverage site` on attached project [minimal-junit5-pitest-v0.12.zip](https://github.com/pitest/pitest-junit5-plugin/files/4411731/minimal-junit5-pitest-v0.12.zip), I get the error `Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!`.

Full maven output with -X attached [mvn.out.txt](https://github.com/pitest/pitest-junit5-plugin/files/4411735/mvn.out.txt)).

When changing `pitest-junit5-plugin` to version `0.8`, everything works fine with two SURVIVED mutations.
When changing `pitest-junit5-plugin` to version `0.9`, the build does not fail but report shows NO_COVERAGE on all mutations.
When changing `pitest-junit5-plugin` to version `0.10`, `0.11` and `0.12` - the build fails with an error.

Two relevant stack traces in the output file:
1.
```
    at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData (DefaultCoverageGenerator.java:148)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage (DefaultCoverageGenerator.java:89)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage (DefaultCoverageGenerator.java:51)
    at org.pitest.mutationtest.tooling.MutationCoverage.runReport (MutationCoverage.java:115)
    at org.pitest.mutationtest.tooling.EntryPoint.execute (EntryPoint.java:121)
    at org.pitest.mutationtest.tooling.EntryPoint.execute (EntryPoint.java:51)
    at org.pitest.maven.RunPitStrategy.execute (RunPitStrategy.java:35)
...
```

2.
```
    at org.pitest.util.Unchecked.translateCheckedException (Unchecked.java:20)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage (DefaultCoverageGenerator.java:105)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage (DefaultCoverageGenerator.java:51)
    at org.pitest.mutationtest.tooling.MutationCoverage.runReport (MutationCoverage.java:115)
    at org.pitest.mutationtest.tooling.EntryPoint.execute (EntryPoint.java:121)
    at org.pitest.mutationtest.tooling.EntryPoint.execute (EntryPoint.java:51)
    at org.pitest.maven.RunPitStrategy.execute (RunPitStrategy.java:35)
    at org.pitest.maven.AbstractPitMojo.analyse (AbstractPitMojo.java:463)
    at org.pitest.maven.AbstractPitMojo.execute (AbstractPitMojo.java:404)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
...
```

This project is based on https://github.com/tomekkaczanowski/minimal-junit5-pitest with few version upgrades.

**Comment by magwas** [comment]
I have the same error message, I do not know whether the underlying cause is the same.

I think the following is the relevant part:
org.pitest.junit5.JUnit5TestUnitFinder does not define or inherit an implementation of the resolved method 'abstract java.util.List findTestUnits(java.lang.Class)' of interface org.pitest.testapi.TestUnitFinder.

It runs fine with maven, but when I try to Run as PIT Mutation Test from eclipse, it does happen.

console output:

8:29:04 PM PIT >> INFO : ---------------------------------------------------------------------------
8:29:04 PM PIT >> INFO : Enabled (+) and disabled (-) features.
8:29:04 PM PIT >> INFO : -----------------------------------------
8:29:04 PM PIT >> INFO : +FANN           Filters mutations in classes and methods with matching annotations of class or runtime retention
8:29:04 PM PIT >> INFO :   [annotation]    Annotation to avoid (full package name not required)
8:29:04 PM PIT >> INFO : +FENUM          Filters mutations in enum constructors
8:29:04 PM PIT >> INFO : +FFBLOCK        Filters mutations in code duplicated by finally block inlining
8:29:04 PM PIT >> INFO : +FFEACH         Filters mutations in compiler generated code that implements for each loops
8:29:04 PM PIT >> INFO : +FFLOOP         Filters any mutations to increments in for loops as they may cause timeouts
8:29:04 PM PIT >> INFO : +FINFINC        Filters mutations to increments that may cause infinite loops
8:29:04 PM PIT >> INFO : +FINFIT         Filters mutations that may cause infinite loops by removing calls to iterator.next
8:29:04 PM PIT >> INFO : +FINULL         Filters mutations in compiler generated code that checks for null by calling getClass
8:29:04 PM PIT >> INFO : +FKOTLIN        Filters out junk mutations in bytecode created by compiler for kotlin language features
8:29:04 PM PIT >> INFO : +FLOGCALL       Filters mutations in code that makes calls to logging frameworks
8:29:04 PM PIT >> INFO : +FMRNULL        Filters mutations in compiler generated code that inserts Objects.requireNonNull for method references
8:29:04 PM PIT >> INFO : +FRETEQUIV      Filters return vals mutants with bytecode equivalent to the unmutated class
8:29:04 PM PIT >> INFO : +FSEQUIVEQUALS  Filters equivalent mutations that affect only performance in short cutting equals methods
8:29:04 PM PIT >> INFO : +FSTATI         Filters mutations in static initializers and code called only from them
8:29:04 PM PIT >> INFO : +FSTATINIT      Filters mutations in static initializers and code called only from them
8:29:04 PM PIT >> INFO : +FTRYWR         Filters mutations in code generated for try with resources statements
8:29:04 PM PIT >> INFO : +_internal_activate_by_output_string
8:29:04 PM PIT >> INFO : -CLASSLIMIT     Limits the maximum number of mutations per class
8:29:04 PM PIT >> INFO :   [limit]         Integer value for maximum mutations to create per class
8:29:04 PM PIT >> INFO : -EXPORT         Exports mutants bytecode and other details to disk
8:29:04 PM PIT >> INFO : ---------------------------------------------------------------------------
8:29:04 PM PIT >> FINE : Running report with ReportOptions [targetClasses=[civitas.crypto.keyshare.ElGamalKeyShareFromXML, civitas.crypto.publickeyciphertext.EncryptPublic, civitas.crypto.CryptoFactory, civitas.crypto.rsapublickey.ObtainRSASigner, civitas.crypto.msg.ElGamalMsg, civitas.crypto.rsakeypair.KeyPair, civitas.crypto.proofknowndisclog.VerifyElGamalProofKnowDiscLog, civitas.crypto.parameters.CalculateNumberOfPrimeTests, civitas.crypto.proofvote.VerifyProofVote, civitas.crypto.ciphertext.MultiplyCiphertexts, civitas.common.VoterSubmission, civitas.crypto.ciphertext.ElGamalCiphertextToXML, civitas.crypto.petdecommitment.ConstructPETDecommitment, civitas.crypto.proofdisclog.ElGamalProofDiscLogEqualityFromXML, civitas.crypto.proofknowndisclog.ElGamalProofKnowDiscLogToXML, civitas.crypto.petshare.PetShareFromXML, civitas.crypto.sharedkeyciphertext.SharedKeyCiphertext, civitas.crypto.proof1ofl.VerifyElGamalProof1OfL, civitas.crypto.decriptionshare.VerifyElGamalDecryptionShare, civitas.crypto.petcommitment.PETCommitmentToXML, civitas.crypto.proofvote.ProofVoteFromXML, civitas.crypto.rsapublickey.PublicKeyFromXML, civitas.crypto.ciphertextlist.CiphertextListfromXML, civitas.crypto.petdecommitment.PETDecommitment, civitas.crypto.rsaprivatekey.PrivatekeyFromFile, civitas.crypto.algorithms.ConvertToBase64, civitas.crypto.petdecommitment.PetDecommitmentFromXML, civitas.crypto.sharedkey.GetSharedKeyGenerator, civitas.common.Ballot, civitas.crypto.ciphertextlist.CiphertextListToXML, civitas.crypto.votecapability.VoteCapabilityToXML, civitas.crypto.keypair.GenerateElGamalKeyPair, civitas.crypto.proof1ofl.ElGamalProof1OfLFromXML, civitas.crypto.proofdvr.FakeElGamalProofDVR, civitas.crypto.votecapabilityshare.VoteCapabilityShare, civitas.crypto.oneoflreencryption.ElGamal1OfLReencryption, civitas.crypto.publickeymsg.PublicKeyMsg, civitas.crypto.sharedkey.SharedKeyToXML, civitas.crypto.sharedkey.CreateSharedKeyFromBytes, civitas.crypto.petdecommitment.PetCommitmentFromXML, civitas.crypto.reencryptfactor.ElGamalReencryptFactorFromXML, civitas.crypto.keyshare.CombineKeyShares, civitas.crypto.proof1ofl.ConstructWellKnownCiphertexts, civitas.crypto.algorithms.CreateFreshNonceBase64, civitas.crypto.signature.VerifyElGamalSignature, civitas.crypto.parameters.ElGamalParametersToXML, civitas.crypto.proofdvr.ConstructElGamalProofDVR, civitas.crypto.algorithms.ConvertHashToBigInt, civitas.crypto.rsapublickey.PublicKey, civitas.crypto.rsapublickey.PublicKeyToXML, civitas.crypto.proofvote.ConstructProofVote, civitas.crypto.votecapability.VoteCapabilityFromXML, civitas.crypto.signature.SignatureToXML, civitas.util.InitialTests, civitas.crypto.parameters.PrimePair, civitas.crypto.proof1ofl.ConstructElGamalProof1OfL, civitas.crypto.rsapublickey.VerifyPublicKeySignature, civitas.crypto.rsaprivatekey.PrivateKey, civitas.util.Use, civitas.crypto.decriptionshare.ConstructElGamalDecryptionShare, civitas.crypto.parameters.LegendreSymbol, civitas.crypto.decriptionshare.ElGamalDecryptionShareToXML, civitas.common.VerifiableVoteToXML, civitas.crypto.algorithms.CreateFreshNonce, civitas.crypto.votecapabilityshare.VoteCapabilityShareToXML, civitas.crypto.publickeyciphertext.PublicKeyCiphertextToXML, civitas.crypto.keyshare.ElGamalKeyShareToXML, civitas.crypto.parameters.GenerateSafePrime, civitas.common.XMLSerializable, civitas.crypto.proofdisclog.ElGamalProofDiscLogEquality, civitas.crypto.messagedigest.ObtainMessageDigest, civitas.util.Boilerplate, civitas.crypto.publickey.ElGamalPublicKeyToXML, civitas.crypto.keypairshare.ElGamalKeyPairShare, civitas.crypto.proofknowndisclog.ElGamalProofKnowDiscLog, civitas.crypto.algorithms.GetRandomGenerator, civitas.crypto.proofdisclog.VerifyElGamalProofDiscLogEquality, civitas.crypto.oneoflreencryption.ConstructElGamal1OfLReencryption, civitas.util.CivitasBigInteger, civitas.common.CondorcetBallot, civitas.crypto.oneoflreencryption.ElGamal1OfLReencryptionToXML, civitas.crypto.parameters.encoder.SafePrimeEncode, civitas.crypto.sharedkey.GenerateSharedKey, civitas.crypto.proofknowndisclog.ElGamalProofKnowDiscLogFromXML, civitas.crypto.privatekey.ElGamalPrivateKey, civitas.crypto.algorithms.CreatePermutation, civitas.crypto.parameters.encoder.SafePrimeDecode, civitas.crypto.proof1ofl.VerifyElGamal1OfLReencryption, civitas.crypto.CryptoUtil, civitas.crypto.keyshare.ElGamalKeyShare, civitas.common.Util, civitas.crypto.rsapublickey.CreatePublicKeyFromBytes, civitas.crypto.petcommitment.PETCommitment, civitas.crypto.ciphertext.ElGamalEncrypt, civitas.crypto.proof1ofl.ElGamalProof1OfL, civitas.crypto.proofdvr.VerifyElGamalProofDVR, civitas.crypto.rsaprivatekey.PrivateKeyFromXML, civitas.crypto.sharedkey.SharedKey, civitas.crypto.parameters.DecodeChoice, civitas.crypto.keyshare.VerifyElGamalKeyShare, civitas.crypto.parameters.encoder.SchnorrPrimeEncode, civitas.crypto.decriptionshare.CombineDecryptionShares, civitas.crypto.proof1ofl.ElGamalProof1OfLToXML, civitas.crypto.sharedkey.DecryptShared, civitas.crypto.oneoflreencryption.ElGamal1OfLReencryptionFromXML, civitas.crypto.proofdvr.ElGamalProofDVR, civitas.crypto.signature.SignatureFromXML, civitas.crypto.signedciphertext.SharedKeyCiphertextFromXML, civitas.crypto.parameters.FindGenerator, civitas.crypto.sharedkey.SharedKeyFromXML, civitas.crypto.ciphertext.ElGamalCiphertext, civitas.crypto.sharedkeyciphertext.EncryptShared, civitas.crypto.petcommitment.ConstructPETCommitment, civitas.crypto.publickey.ElGamalPublicKeyFromFile, civitas.crypto.publickey.ElGamalPublicKeyFromXML, civitas.crypto.signature.Signature, civitas.crypto.algorithms.ConvertToBigInt, civitas.crypto.sharedkey.SharedKeyToWire, civitas.crypto.votecapabilityshare.VoteCapabilityShareFromXML, civitas.crypto.proofvote.ProofVote, civitas.crypto.signedciphertext.ElGamalSignedCiphertextToXML, civitas.crypto.Constants, civitas.common.CondorcetBallotDesign, civitas.crypto.parameters.GenerateSchnorrPrime, civitas.common.CondorcetTallyState, civitas.crypto.rsapublickey.IsPublicKeyAuthorized, civitas.crypto.signedciphertext.ElGamalSignedCiphertext, civitas.common.VerifiableVote, civitas.crypto.reencryptfactor.GenerateElGamalReencryptFactor, civitas.util.ObtainProbablePrime, civitas.crypto.votecapabilityshare.GenerateVoteCapabilityShare, civitas.crypto.petdecommitment.PETDecommitmentToXML, civitas.crypto.proofvote.CalculateProofEnvironment, civitas.crypto.parameters.SetUpDecodeMap, civitas.crypto.msg.DecryptElGamalMessage, civitas.crypto.proofdisclog.ConstructElGamalDiscLogEqualityProof, civitas.crypto.signedciphertext.ElGamalSignedCiphertextFromXML, civitas.crypto.petshare.PETShare, civitas.crypto.CryptoError, civitas.crypto.proofdvr.ElGamalProofDVRFromXML, civitas.crypto.privatekey.ElGamalPrivateKeyFromFile, civitas.crypto.publickeyciphertext.PublicKeyCiphertextFromXML, civitas.crypto.decriptionshare.ElGamalDecryptionShare, civitas.crypto.algorithms.GetPublicKeyGenerator, civitas.common.XMLDeserializer, civitas.crypto.votecapabilityshare.CombineVoteCapabilityShares, civitas.crypto.CryptoFactoryC, civitas.crypto.parameters.ElGamalParameters, civitas.crypto.rsakeypair.GenerateKeyPair, civitas.util.Tested, civitas.crypto.petcommitment.IsPetResult, civitas.crypto.sharedkey.SharedKeyFromWire, civitas.crypto.ciphertextlist.CiphertextList, civitas.crypto.external.DoCrypto, civitas.crypto.keypairshare.GenerateKeyPairShare, civitas.crypto.parameters.GenerateElGamalParameters, civitas.crypto.petshare.PETShareToXML, civitas.crypto.petshare.ConstructPETShare, civitas.crypto.publickey.ElGamalPublicKey, civitas.crypto.keyshare.ConstructElGamalKeyShare, civitas.crypto.proofvote.ProofVoteToXML, civitas.crypto.proofknowndisclog.ConstructProofKnowDiscLog, civitas.crypto.parameters.encoder.SchnorrPrimeDecode, civitas.crypto.messagedigest.MessageDigest, civitas.crypto.ciphertext.ElGamalCiphertextFromXML, civitas.crypto.keypairshare.ElGamalKeyPairShareFromXML, civitas.crypto.proofdvr.ElGamalProofDVRToXML, civitas.crypto.CryptoException, civitas.crypto.petdecommitment.VerifyPETDecommitment, civitas.crypto.rsapublickey.PublicKeyFromFile, civitas.util.DI, civitas.crypto.votecapability.VoteCapability, civitas.crypto.rsapublickey.DecryptPublic, civitas.crypto.publickey.ElGamalPublicKeyisAuthorized, civitas.crypto.sharedkeyciphertext.SharedKeyCiphertextToXML, civitas.common.TallyState, civitas.crypto.reencryptfactor.ElGamalReencryptFactorToXML, civitas.crypto.privatekey.ElGamalPrivateKeyFromXML, civitas.common.CondorcetTallyStateFinal, civitas.crypto.msg.EncodeMessage, civitas.crypto.rsaprivatekey.PrivateKeyToXML, civitas.crypto.signature.SignWithPublicKey, civitas.crypto.keypair.ElGamalKeyPair, civitas.crypto.algorithms.GenerateRandomInt, civitas.common.BallotDesign, civitas.crypto.publickeymsg.VerifyPublicKeySignatureMsg, civitas.crypto.sharedkeymsg.SharedKeyMsg, civitas.crypto.proofdisclog.ElGamalProofDiscLogEqualityToXML, civitas.common.TallyStateFinal, civitas.crypto.signedciphertext.SignAndEncrypt, civitas.crypto.keypairshare.ElGamalKeyPairShareToXML, civitas.crypto.messagedigest.CryptoHash, civitas.crypto.ciphertextlist.ConstructCiphertextList, civitas.crypto.parameters.ElGamalParametersFromXML, civitas.crypto.rsaprivatekey.CreatePrivateKeyFromBytes, civitas.crypto.ciphertext.ElGamalReencrypt, civitas.crypto.decriptionshare.ElGamalDecryptionShareFromXML, civitas.crypto.parameters.CheckGroup, civitas.crypto.publickey.GetElGamalPublicKeyName, civitas.crypto.petcommitment.CombinePETShareDecommitments, civitas.crypto.algorithms.GenerateRandomElement, civitas.crypto.privatekey.ElGamalPrivateKeyToXML, civitas.crypto.publickeyciphertext.PublicKeyCiphertext, civitas.crypto.reencryptfactor.ElGamalReencryptFactor], excludedMethods=[], excludedClasses=[*Test], excludedTestClasses=[], codePaths=[], reportDir=/home/mag/eclipse-workspace/.metadata/.plugins/org.pitest.pitclipse.core/html_results, historyInputLocation=null, historyOutputLocation=null, sourceDirs=[/home/mag/project/civitas-0.7.1/jcivitas/src/test/java, /home/mag/project/civitas-0.7.1/jcivitas/src/main/resources, /home/mag/project/civitas-0.7.1/jcivitas/src/test/resources, /home/mag/project/civitas-0.7.1/jcivitas/src/main/java], classPathElements=[/home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839, /home/mag/.p2/pool/plugins/org.pitest.pitclipse.runner_2.2.1.v20230330-0839.jar, /home/mag/.p2/pool/plugins/org.pitest.pitclipse.runner_2.2.1.v20230330-0839.jar/target/classes, /home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839/lib/pitest.jar, /home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839/lib/pitest-entry.jar, /home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839/lib/pitest-command-line.jar, /home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839/lib/pitest-html-report.jar, /home/mag/.p2/pool/plugins/org.pitest.pitclipse.listeners_2.2.1.v20230330-0839.jar, /home/mag/.p2/pool/plugins/org.pitest.pitclipse.listeners_2.2.1.v20230330-0839.jar/target/classes, /home/mag/project/civitas-0.7.1/jcivitas/target/classes, /home/mag/project/civitas-0.7.1/jcivitas/target/test-classes, /home/mag/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.12.1/junit-jupiter-api-5.12.1.jar, /home/mag/.m2/repository/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar, /home/mag/.m2/repository/org/junit/platform/junit-platform-commons/1.12.1/junit-platform-commons-1.12.1.jar, /home/mag/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar, /home/mag/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.12.1/junit-jupiter-engine-5.12.1.jar, /home/mag/.m2/repository/org/junit/platform/junit-platform-engine/1.12.1/junit-platform-engine-1.12.1.jar, /home/mag/.m2/repository/org/junit/platform/junit-platform-launcher/1.12.1/junit-platform-launcher-1.12.1.jar, /home/mag/.m2/repository/org/mockito/mockito-core/5.18.0/mockito-core-5.18.0.jar, /home/mag/.m2/repository/net/bytebuddy/byte-buddy/1.17.5/byte-buddy-1.17.5.jar, /home/mag/.m2/repository/net/bytebuddy/byte-buddy-agent/1.17.5/byte-buddy-agent-1.17.5.jar, /home/mag/.m2/repository/org/objenesis/objenesis/3.3/objenesis-3.3.jar, /home/mag/.m2/repository/org/bouncycastle/bcprov-jdk18on/1.80/bcprov-jdk18on-1.80.jar, /home/mag/.m2/repository/org/projectlombok/lombok/1.18.36/lombok-1.18.36.jar, /home/mag/.m2/repository/org/pitest/pitest-junit5-plugin/1.2.3/pitest-junit5-plugin-1.2.3.jar, /home/mag/.p2/pool/plugins/org.pitest.pitest-junit5-plugin_0.14.0.v20230330-0839/lib/pitest-junit5-plugin.jar], mutators=[DEFAULTS], features=[], dependencyAnalysisMaxDistance=-1, jvmArgs=[-Djava.awt.headless=true], numberOfThreads=4, timeoutFactor=1.25, timeoutConstant=3000, targetTests=[^civitas\.crypto\.messagedigest\..*$], loggingClasses=[java.util.logging, org.apache.log4j, org.slf4j, org.apache.commons.logging, org.apache.logging.log4j], verbose=true, failWhenNoMutations=false, outputs=[HTML, PITCLIPSE_MUTATIONS, PITCLIPSE_SUMMARY], groupConfig=TestGroupConfig [excludedGroups=[], includedGroups=[]], fullMutationMatrix=false, mutationUnitSize=0, shouldCreateTimestampedReports=true, detectInlinedCode=false, exportLineCoverage=false, mutationThreshold=0, testStrengthThreshold=0, coverageThreshold=0, mutationEngine=gregor, javaExecutable=null, includeLaunchClasspath=true, properties={}, maxSurvivors=-1, excludedRunners=[], includedTestMethods=[], testPlugin=junit5, useClasspathJar=false, skipFailingTests=false]
8:29:04 PM PIT >> FINE : System class path is /home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839:/home/mag/.p2/pool/plugins/org.pitest.pitclipse.runner_2.2.1.v20230330-0839.jar:/home/mag/.p2/pool/plugins/org.pitest.pitclipse.runner_2.2.1.v20230330-0839.jar/target/classes:/home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839/lib/pitest.jar:/home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839/lib/pitest-entry.jar:/home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839/lib/pitest-command-line.jar:/home/mag/.p2/pool/plugins/org.pitest_1.6.8.v20230330-0839/lib/pitest-html-report.jar:/home/mag/.p2/pool/plugins/org.pitest.pitclipse.listeners_2.2.1.v20230330-0839.jar:/home/mag/.p2/pool/plugins/org.pitest.pitclipse.listeners_2.2.1.v20230330-0839.jar/target/classes:/home/mag/project/civitas-0.7.1/jcivitas/target/classes:/home/mag/project/civitas-0.7.1/jcivitas/target/test-classes:/home/mag/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.12.1/junit-jupiter-api-5.12.1.jar:/home/mag/.m2/repository/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar:/home/mag/.m2/repository/org/junit/platform/junit-platform-commons/1.12.1/junit-platform-commons-1.12.1.jar:/home/mag/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/home/mag/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.12.1/junit-jupiter-engine-5.12.1.jar:/home/mag/.m2/repository/org/junit/platform/junit-platform-engine/1.12.1/junit-platform-engine-1.12.1.jar:/home/mag/.m2/repository/org/junit/platform/junit-platform-launcher/1.12.1/junit-platform-launcher-1.12.1.jar:/home/mag/.m2/repository/org/mockito/mockito-core/5.18.0/mockito-core-5.18.0.jar:/home/mag/.m2/repository/net/bytebuddy/byte-buddy/1.17.5/byte-buddy-1.17.5.jar:/home/mag/.m2/repository/net/bytebuddy/byte-buddy-agent/1.17.5/byte-buddy-agent-1.17.5.jar:/home/mag/.m2/repository/org/objenesis/objenesis/3.3/objenesis-3.3.jar:/home/mag/.m2/repository/org/bouncycastle/bcprov-jdk18on/1.80/bcprov-jdk18on-1.80.jar:/home/mag/.m2/repository/org/projectlombok/lombok/1.18.36/lombok-1.18.36.jar:/home/mag/.m2/repository/org/pitest/pitest-junit5-plugin/1.2.3/pitest-junit5-plugin-1.2.3.jar:/home/mag/.p2/pool/plugins/org.pitest.pitest-junit5-plugin_0.14.0.v20230330-0839/lib/pitest-junit5-plugin.jar
8:29:04 PM PIT >> FINE : Maximum available memory is 7996 mb
8:29:05 PM PIT >> FINE : Could not find java/lang/ArrayIndexOutOfBoundsException on classpath for analysis. Falling back to classloader
8:29:05 PM PIT >> FINE : Could not find java/lang/String on classpath for analysis. Falling back to classloader
8:29:05 PM PIT >> FINE : Could not find java/lang/IndexOutOfBoundsException on classpath for analysis. Falling back to classloader
8:29:05 PM PIT >> FINE : Could not find java/lang/RuntimeException on classpath for analysis. Falling back to classloader
8:29:05 PM PIT >> FINE : Could not find java/lang/Exception on classpath for analysis. Falling back to classloader
8:29:05 PM PIT >> FINE : Could not find java/lang/Throwable on classpath for analysis. Falling back to classloader
8:29:05 PM PIT >> FINE : Could not find java/lang/Object on classpath for analysis. Falling back to classloader
8:29:05 PM PIT >> FINE : Could not find java/lang/NullPointerException on classpath for analysis. Falling back to classloader
8:29:06 PM PIT >> FINE : Incremental analysis set 1568 mutations to a status of NOT_STARTED
8:29:06 PM PIT >> INFO : Incremental analysis reduced number of mutations by 0
8:29:06 PM PIT >> INFO : Created  159 mutation test units in pre scan
8:29:06 PM PIT >> FINE : MINION : Installing PIT agent
8:29:06 PM PIT >> INFO : Sending 6 test classes to minion
8:29:06 PM PIT >> INFO : Sent tests to minion
8:29:07 PM PIT >> INFO : MINION : 8:29:06 PM PIT >> FINE : Expecting 6 tests classes from parent
8:29:07 PM PIT >> INFO : MINION : 8:29:06 PM PIT >> FINE : Tests classes received
8:29:07 PM PIT >> INFO : MINION : 8:29:07 PM PIT >> INFO : Checking environment
8:29:07 PM PIT >> FINE : MINION : java.lang.AbstractMethodError: Receiver class org.pitest.junit5.JUnit5TestUnitFinder does not define or inherit an implementation of the resolved method 'abstract java.util.List findTestUnits(java.lang.Class)' of interface org.pitest.testapi.TestUnitFinder.
8:29:07 PM PIT >> FINE : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestUnitFinder.findTestUnits(PrioritisingTestUnitFinder.java:19)
8:29:07 PM PIT >> FINE : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:57)
8:29:07 PM PIT >> FINE : MINION : 	at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
8:29:07 PM PIT >> FINE : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
8:29:07 PM PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:155)
8:29:07 PM PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:136)
8:29:07 PM PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:83)
8:29:07 PM PIT >> INFO : MINION : 8:29:07 PM PIT >> SEVERE : Error calculating coverage. Process will exit.
8:29:07 PM PIT >> INFO : MINION : java.lang.AbstractMethodError: Receiver class org.pitest.junit5.JUnit5TestUnitFinder does not define or inherit an implementation of the resolved method 'abstract java.util.List findTestUnits(java.lang.Class)' of interface org.pitest.testapi.TestUnitFinder.
8:29:07 PM PIT >> INFO : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestUnitFinder.findTestUnits(PrioritisingTestUnitFinder.java:19)
8:29:07 PM PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:57)
8:29:07 PM PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
8:29:07 PM PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
8:29:07 PM PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:155)
8:29:07 PM PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:136)
8:29:07 PM PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:83)
8:29:07 PM PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Eclipse Adoptium
Version : 17.0.8.1+1
Uptime : 3530
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Dstdout.encoding=UTF-8
 3 : -Dstderr.encoding=UTF-8
 4 : -XX:+ShowCodeDetailsInExceptionMessages
BootClassPathSupported : false


Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Eclipse Adoptium
Version : 17.0.8.1+1
Uptime : 3536
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Dstdout.encoding=UTF-8
 3 : -Dstderr.encoding=UTF-8
 4 : -XX:+ShowCodeDetailsInExceptionMessages
BootClassPathSupported : false

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:106)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:52)
	at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:149)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:139)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:125)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:52)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
	at org.pitest.pitclipse.runner.PitRunner.apply(PitRunner.java:35)
	at org.pitest.pitclipse.runner.PitRunner.apply(PitRunner.java:1)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.pitest.pitclipse.runner.PitRunnerMain.main(PitRunnerMain.java:38)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Eclipse Adoptium
Version : 17.0.8.1+1
Uptime : 3530
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Dstdout.encoding=UTF-8
 3 : -Dstderr.encoding=UTF-8
 4 : -XX:+ShowCodeDetailsInExceptionMessages
BootClassPathSupported : false

	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:149)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:90)
	... 11 more
